# Generated by Django 5.1.6 on 2025-02-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('role', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('starting', models.DateField(max_length=255)),
                ('ending', models.DateField(max_length=255)),
            ],
        ),
    ]
